"""Expose a raggity knowledge base as an MCP (Model Context Protocol) server.

The server speaks MCP over **stdio**, so an MCP client (Claude Code, Claude
Desktop, Cursor, ...) can register raggity as a native tool and query the local
knowledge base directly.  Three tools are exposed:

- ``search``    — raw retrieval (no LLM, abstention bypassed); packed context
  blocks for the *agent's own* reasoning.
- ``ask``       — the full raggity RAG pipeline; a cited answer (or the KB's
  own abstention message) generated by raggity's configured model.
- ``kb_status`` — a cheap store-only summary (chunk/source counts + backend).

The heavy ``mcp`` dependency is imported lazily inside :func:`build_mcp` so that
``import raggity.cli`` (and the rest of the package) stays fast and does not
require the optional ``raggity[mcp]`` extra.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover - typing only
    from mcp.server.fastmcp import FastMCP

    from .core import Raggity

# User-facing hint when the optional extra is missing.
MCP_EXTRA_HINT = "The MCP server needs extra deps: pip install raggity[mcp]"


def build_mcp(rag: "Raggity") -> "FastMCP":
    """Build a :class:`FastMCP` server exposing *rag* as search/ask/kb_status tools.

    Raises :class:`ImportError` (with :data:`MCP_EXTRA_HINT`) when the ``mcp``
    package is not installed.  The tools close over *rag*; no global state.
    """
    try:
        import anyio
        from mcp.server.fastmcp import FastMCP
    except ImportError as exc:  # pragma: no cover - exercised via CLI test
        raise ImportError(MCP_EXTRA_HINT) from exc

    from .packing import pack_context

    mcp = FastMCP(
        "raggity",
        instructions=(
            "Query a local raggity knowledge base of the user's own notes, "
            "documents, and code. Use `search` when you want raw source passages "
            "to reason over yourself; use `ask` when you want raggity to produce a "
            "cited, grounded answer from the knowledge base; use `kb_status` to see "
            "how much is indexed."
        ),
    )

    @mcp.tool()
    async def search(query: str, k: int = 8,
                     max_context_tokens: int | None = None) -> str:
        """Retrieve raw passages from the knowledge base (no answer generation).

        Returns the top-``k`` most relevant chunks packed into a single context
        string, each as a ``[source: <path>]`` block separated by blank lines.
        This is retrieval ONLY — no LLM is invoked and the relevance/abstention
        floor is BYPASSED, so you always get the best available matches and decide
        yourself whether they answer the question.

        Prefer `search` over `ask` when you are doing your own reasoning and just
        need grounding material (source snippets to quote, cross-check, or
        synthesise). Use `ask` instead when you want a finished, cited answer from
        the knowledge base's own pipeline.

        Args:
            query: What to look up in the knowledge base.
            k: Max number of chunks to return (default 8).
            max_context_tokens: Optional budget; when set, chunks are greedily
                packed until adding the next would exceed it (chars/4 approx).
        """
        chunks = await anyio.to_thread.run_sync(
            lambda: rag.retriever.retrieve(query, top_k=k, apply_sufficiency=False))
        packed, _ = pack_context(chunks, max_context_tokens)
        if not packed:
            return ("(no results: the knowledge base returned no matching context "
                    "for this query.)")
        return packed

    @mcp.tool()
    async def ask(question: str) -> str:
        """Answer a question using the knowledge base's full RAG pipeline.

        Runs raggity's retrieve-then-generate pipeline (its configured model,
        grounding, and citation verification) and returns the answer text followed
        by a "Sources:" footer listing the cited source paths. If the knowledge
        base lacks enough information, raggity abstains and that abstention message
        is returned verbatim (no fabricated answer).

        Prefer `ask` when you want a finished, grounded answer straight from the
        knowledge base. Use `search` instead when you only need raw passages to
        reason over yourself.

        Args:
            question: The question to answer from the knowledge base.
        """
        answer = await rag.aask(question)
        if answer.abstained:
            return answer.text
        text = answer.text
        seen: list[str] = []
        for c in answer.citations:
            if c.supported and c.source_path not in seen:
                seen.append(c.source_path)
        if seen:
            text += "\n\nSources:\n" + "\n".join(f"- {s}" for s in seen)
        return text

    @mcp.tool()
    async def kb_status() -> str:
        """Summarise what the knowledge base currently contains.

        Cheap and store-only: reports the number of indexed chunks, the number of
        distinct source documents, and the vector index backend. Does NOT build
        the embedder, reranker, or LLM provider. Call this to gauge coverage
        before deciding whether `search`/`ask` are worth running.
        """
        def _counts() -> tuple[int, int]:
            return rag.store.count(), len(rag.store.all_source_paths())

        chunks, sources = await anyio.to_thread.run_sync(_counts)
        return (f"chunks: {chunks}\n"
                f"sources: {sources}\n"
                f"index_backend: {rag.cfg.index.backend}")

    return mcp


def run_mcp(config_path: str | None = None) -> None:
    """Build a :class:`Raggity` from *config_path* and serve it over stdio MCP.

    Blocks until the client disconnects. Nothing is written to stdout before the
    stdio transport takes over (raggity construction is silent; logging goes to
    stderr), so the JSON-RPC pipe stays uncorrupted.
    """
    from .core import Raggity

    rag = Raggity.from_config(config_path)
    # Warm the retrieval stack (embedder/store/reranker) on the MAIN thread
    # BEFORE the stdio loop starts. The first `search` otherwise lazily imports
    # numpy/onnxruntime C extensions inside an anyio worker thread, which
    # deadlocks on the Windows DLL loader lock under the stdio transport
    # (observed live: worker stuck in numpy create_module, server hung).
    # Warming here also makes the first tool call fast.
    _ = rag.retriever
    mcp = build_mcp(rag)
    mcp.run()  # transport defaults to "stdio"
